config/routes.rb
# Plugin"s routes
# See: http://guides.rubyonrails.org/routing.html

GollumRails::Engine.routes.draw do

  get  "/index" => "wiki#index",     :as => :wiki_root
  post "/preview" => "wiki#preview", :as => :wiki_preview
  get  "/list/:str" => "wiki#list",  :as => :wiki_list
  match "/new" => "wiki#new_page" ,  :as => :new_wiki_page , :via => [:get , :post]

  constraints( :page => /.*/ ) do
    match "/edit/:page" => "wiki#edit" ,   :as => :edit_wiki_page   , :via => [:get , :post]
    match "/rename/:page" => "wiki#rename",:as => :rename_wiki_page , :via => [:get , :post]
    match "/delete/:page" => "wiki#delete",:as => :delete_wiki_page , :via => [:get , :post]
    get ":page" => "wiki#page" ,           :as => :wiki_page
  end

end

app/models/wiki.rb
# use our own wiki class just so we have a way to extend the gollum-lib stuff

# This is singleton, ie only ever one instance is supported and you can get that instance 
# with the wiki class method

class Wiki < Gollum::Wiki
  @@wiki = nil
  # reader for class attribute :wiki
  def self.wiki
    @@wiki || init_wiki
  end

  def self.page_class
    WikiPage
  end
  # The singleton wiki (currently) is instantiated from the after_init in the engine
  # this can definately be improved, but it's a nice low key start
  def self.init_wiki path = Rails.application.config.wiki_path
    path = Rails.root.join(path) if path.starts_with?("/")
    begin
      @@wiki = Wiki.new(path)
    rescue Gollum::NoSuchPathError
      puts "No path #{path}"
      raise
    end
    @@wiki
  end

  def initiaize path
    super(path , :page_class => Wiki)
  end
  # Find an existing page or create it
  #
  # name - The name
  # commit - Hash
  #
  # Returns self
  def find_or_initialize_by_name(name, commit={})
    result = find(name)
    if result
      result
    else
      WikiPage.new(:format => :markdown, :name => name, :content => ".", :commit => commit)
    end
  end

  # Finds a page based on the name and specified version
  #
  # name - the name of the page
  #
  # Return an instance of Gollum::Page
  def find(name, version=nil)
    paged(name)
  end

  # == Searches the wiki for files CONTENT!
  #
  # string - Searchstring
  #
  # Returns an Array
  def search(string)
    wiki.search(string)
  end

  # Gets all pages in the wiki
  #
  # Returns an Array with GollumRails::Page s
  def all(options={})
    set_folder(options)
    pages = wiki.pages
    pages.map do |page|
      self.new(gollum_page: page)
    end
  end

end

app/models/wiki_page.rb
# Basic model of a page, for access to content etc

# Pages are stored in a git, not db

# The Wiki class (in lib) is to us what a db-connection would be to AR-model

class WikiPage

  attr_reader :name , :ext , :oid
  attr_accessor :content

  # init from an exising git entry
  def self.init_entry entry
    name , ext = entry[:name].split(".")
    entry[:name] = name
    entry[:ext] = ext
    WikiPage.new entry
  end

  #Initialize from a hash that may have all the attributes set
  def initialize(entry)
    @name = entry[:name]
    @ext = entry[:ext] || :md
    @oid = entry[:oid]
    @content = entry[:content]
  end

  def to_param
    @name
  end

  def content
    return @content unless @content.nil?
    return "" if self.oid.nil?
    WikiPage.wiki.oid_data(self.oid)
  end

  # checks to see if a page by this name is alread in the rep
  def name_exists?
    !WikiPage.wiki.find(self.name).nil?
  end

  # writes the current page data to the git
  # new or old doesn't really matter, git will decide
  def save  message , wiki_user
    WikiPage.wiki.save_page(self, message,  wiki_user)
  end

  def delete  message , wiki_user
    WikiPage.wiki.delete_page(self, message,  wiki_user)
  end

  # rename to the given new name. message and wiki_user like other actions
  def rename( new_name , message ,  wiki_user )
    old_name = @name
    @name = new_name
    sha = WikiPage.wiki.rename_page(self, old_name , message,  wiki_user)
    sha
  end
  ## TODO move this stuff into a concern or something
  ## Note: The wiki is to a WikiPage what a db is to a normal model. ie something like a connection

  @@wiki = nil
  # reader for class attribute :wiki
  def self.wiki
    @@wiki || init_wiki
  end
  # The singleton wiki (currently) is instantiated from the after_init in the engine
  # this can definately be improved, but it's a nice low key start
  def self.init_wiki
    begin
      wiki_path = Rails.application.config.wiki_path
    rescue
      wiki_path = "wiki.git"
    end
    @@wiki = GollumRails::Wiki.new(wiki_path)
  end

end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController

  include GollumRails::Engine.routes.url_helpers

  before_filter :find_page, only: [ :page , :edit , :delete , :rename]

  before_filter :require_user, only: [ :new_page , :edit , :delete , :rename]

  # GET all pages, unpaginated, useful only for small wikis
  def index
    @pages = WikiPage.wiki.pages
  end

  def preview
    render :preview , :layout => false
  end

  # return a list of pages that contain the "str" from /wiki/list/str
  def list
    @pages = WikiPage.wiki.pages( params[:str] )
    render :list , :layout => false
  end

  def new_page
    return unless request.post?
    return if needs_message
    @page = WikiPage.new(params)
    if(@page.name_exists?)
      flash[:error] = "Page name exists, please change #{@page.name}"
      render :edit
    else
      @page.save(params[:message] , wiki_user)
      redirect_to wiki_page_path(@page)
    end
  end

  def edit
    return unless request.post?
    return if needs_message
    @page.content = params[:content]
    @page.save( params[:message] , wiki_user )
    return redirect_to wiki_page_path(@page.name)
  end

  def delete
    return redirect_to wiki_page_path("Home") if @page.name == "Home"
    return unless request.post?
    return if needs_message
    name = @page.name
    @page.delete( params[:message] ,wiki_user)
    flash.notice = "Page deleted "
    return redirect_to wiki_root_path
  end

  def rename
    return redirect_to wiki_page_path("Home") if @page.name == "Home"
    return unless request.post?
    return if needs_message
    @page.rename( params[:name] , params[:message] , wiki_user)
    flash.notice = "Page renamed "
    return redirect_to wiki_page_path(@page.name)
  end

  private

  def needs_message
    if params[:message].blank?
      flash.notice = "message must be given"
      return true
    else
      return false
    end
  end
  def find_page
    redirect_to wiki_root_path if params[:page].blank? 
    @page = WikiPage.wiki.find(params[:page])
    redirect_to new_wiki_page_path(:name => params[:page]), notice: t(:notice_page_does_to_exist) unless @page
  end

  def require_user
    user = wiki_user
    return if user && user.may_edit
    flash.notice = "You may not edit the wiki"
    redirect_to wiki_root_path
  end

end

app/helpers/wiki_helper.rb
module WikiHelper
  def page_rows page
    rows = page.content.split.length + 5
    rows > 30 ? 30 : rows
  end
  def filter content
    context = {       :base_url   => "/wiki"     }
    #      :asset_root => "http://your-domain.com/where/your/images/live/icons",
    #:base_url   => engine.root
    simple = HTML::Pipeline.new [
                            HTML::Pipeline::MarkdownFilter,
                            HTML::Pipeline::TableOfContentsFilter,
                            HTML::Pipeline::SanitizationFilter,
                            HTML::Pipeline::AutolinkFilter,
                            ], context
    simple.call(content)[:output].to_s
  end
end

app/views/wiki/_message.haml
.form_group
  = f.text_field :message , :value => params[:message]
.form_group
  = f.submit t(:submit) , :class => "btn btn-info submit"
  

app/views/wiki/delete.haml
%h3= t(:delete_wiki_page) + " : " + @page.name

%h5 Please give a reason why you want to delete this page
= bootstrap_form_tag :url => delete_wiki_page_path(@page.name) , :html => { :role=>"form"}  do |f|
  = render :partial => "message" , :locals => { :f =>f}
  

app/views/wiki/edit.haml
%h3= t(:edit_wiki_page) + " : " + @page.name

%div{:role => "tabpanel"}
  %ul.nav.nav-tabs#preview_tabs{:role => "tablist"}
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "edit", "data-toggle" => "tab", :href => "#edit", :role => "tab"} Edit
    %li{:role => "presentation"}
      %a.preview_link{"aria-controls" => "preview", :href => "#preview_content", :role => "tab"} Preview
  .tab-content
    #edit.tab-pane.active{:role => "tabpanel"} 
      = bootstrap_form_tag :url => edit_wiki_page_path(@page.name) , :html => { :role=>"form"}  do |f|
        .form_group
          = f.text_area :content , :value => @page.content , :rows => page_rows(@page) , :class => "preview_data"
        = render :partial => "message" , :locals => { :f =>f}
        = link_to t(:cancel) ,   wiki_page_path(@page.name) ,   :class => "btn , btn-info cancel_link"    
    #preview_content.tab-pane{:role => "tabpanel"}
      Loading Preview . . . 

app/views/wiki/index.haml
.row
  .col-md-8
  .col-md-4
    = link_to "new page" , new_wiki_page_path ,    :class => "btn , btn-info edit_link"
.row
  -@pages.each do |page|
    .col-md-4
      = link_to page.name , wiki_page_path(page.name) , :class => :page_link

app/views/wiki/list.haml
%ul
  -@pages.each do |page|
    %li
      = link_to page.name , wiki_page_path(page.name) , :class => :page_link
      

app/views/wiki/new.haml
%h3= t(:new_wiki_page)
= bootstrap_form_tag :url => create_wiki_page_path , :html => { :role=>"form"}  do |f|
  .form_group
    = f.text_field :name
  .form_group
    = f.text_area :content 
  = render :partial => "message" , :locals => { :f =>f}
  

app/views/wiki/new_page.haml
%h3= t(:new_wiki_page)


%div{:role => "tabpanel"}
  %ul.nav.nav-tabs#preview_tabs{:role => "tablist"}
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "edit", "data-toggle" => "tab", :href => "#edit", :role => "tab"} Edit
    %li{:role => "presentation"}
      %a.preview_link{"aria-controls" => "preview", :href => "#preview_content", :role => "tab"} Preview
  .tab-content
    #edit.tab-pane.active{:role => "tabpanel"} 
      = bootstrap_form_tag :url => new_wiki_page_path , :html => { :role=>"form"}  do |f|
        .form_group
          = f.text_field :name , :value =>  params[:name]
        .form_group
          = f.text_area :content , :value => params[:content] , :rows => 10 , :class => "preview_data"
        = render :partial => "message" , :locals => { :f =>f}
        = link_to t(:cancel) ,   wiki_root_path ,   :class => "btn , btn-info cancel_link"    
    #preview_content.tab-pane{:role => "tabpanel"}
      Loading Preview . . . 

  

app/views/wiki/page.haml
= link_to t(:index) ,   wiki_root_path ,   :class => "btn , btn-info root_link"
= link_to t(:edit) ,   edit_wiki_page_path(@page.name) ,   :class => "btn , btn-info edit_link"
= link_to t(:rename) , rename_wiki_page_path(@page.name) , :class => "btn , btn-info rename_link"
= link_to t(:delete) , delete_wiki_page_path(@page.name) , :class => "btn , btn-info delete_link"
= link_to t(:new) , new_wiki_page_path , :class => "btn , btn-info new_link"
%h3=@page.name
= @page.ext
= @page.oid
%br
%br
= raw filter @page.content

app/views/wiki/preview.haml
= raw filter params[:content]

app/views/wiki/rename.haml
%h3= t(:rename_wiki_page) + " : " + @page.name
= bootstrap_form_tag :url => rename_wiki_page_path(@page.name) , :html => { :role=>"form"}  do |f|
  .form_group
    = f.text_field :name , :value => params[:name]
  = render :partial => "message" , :locals => { :f =>f}